<?php
/**
 * Privacy Policy — shared content partial.
 *
 * Included by pages/privacy.php (standalone page).
 * Uses the data-legal attribute for legal document formatting from components.css / pages.css.
 */
?>
<div data-legal>
  <p><strong>Last Updated:</strong> <time datetime="2026-04-10">April 10, 2026</time></p>

  <nav aria-label="Table of contents">
    <h2>Contents</h2>
    <ol>
      <li><a href="#who-we-are">Who We Are</a></li>
      <li><a href="#information-we-collect">Information We Collect</a></li>
      <li><a href="#how-we-use">How We Use Your Information</a></li>
      <li><a href="#how-we-share">How We Share Your Information</a></li>
      <li><a href="#cookies">Cookies and Session Data</a></li>
      <li><a href="#data-retention">How Long We Keep Your Information</a></li>
      <li><a href="#data-security">How We Protect Your Information</a></li>
      <li><a href="#your-rights">Your Rights</a></li>
      <li><a href="#children">Children&rsquo;s Privacy</a></li>
      <li><a href="#third-party">Third-Party Services</a></li>
      <li><a href="#data-transfers">International Data Transfers</a></li>
      <li><a href="#changes">Changes to This Policy</a></li>
      <li><a href="#contact">Contact Us</a></li>
    </ol>
  </nav>

  <section id="who-we-are">
    <h2>Who We Are</h2>
    <p>NeighborhoodTools (<a href="https://neighborhoodtools.org">neighborhoodtools.org</a>) is a neighborhood tool-sharing platform that connects neighbors who want to lend and borrow tools. We are based in the United States.</p>
    <p>For privacy inquiries, contact us at <a href="mailto:contact@neighborhoodtools.org">contact@neighborhoodtools.org</a>.</p>
  </section>

  <section id="information-we-collect">
    <h2>Information We Collect</h2>

    <h3>Information You Provide Directly</h3>
    <p>We collect information you voluntarily provide when you use NeighborhoodTools:</p>
    <ul>
      <li><strong>Account information</strong> &mdash; first name, last name, username, email address, and password (stored as a bcrypt hash; plaintext is never retained) during registration</li>
      <li><strong>Location information</strong> &mdash; ZIP code (required) and street address (optional) during registration and profile editing, plus neighborhood selection (auto-resolved from your address or chosen manually)</li>
      <li><strong>Profile details</strong> &mdash; bio (up to 2,000 characters), profile photo (JPEG, PNG, or WebP, max 5&nbsp;MB) with focal-point coordinates for image cropping, vector avatar selection, and contact preference (email or app)</li>
      <li><strong>Tool listings</strong> &mdash; tool name, description, category, rental fee, condition, loan duration, fuel type (when applicable), and tool photos (JPEG, PNG, or WebP, max 5&nbsp;MB)</li>
      <li><strong>Borrow requests</strong> &mdash; loan duration and optional notes to the lender</li>
      <li><strong>Borrow decisions</strong> &mdash; denial reason (required, up to 1,000 characters) and cancellation reason (optional, up to 1,000 characters)</li>
      <li><strong>Ratings and reviews</strong> &mdash; a 1&ndash;5 star score (required) and optional review text after a completed borrow</li>
      <li><strong>Incident reports</strong> &mdash; description of damage, theft, loss, or other issues, estimated damage amount, and optional photos</li>
      <li><strong>Dispute messages</strong> &mdash; text submitted during dispute resolution</li>
      <li><strong>Waiver acknowledgments</strong> &mdash; three required checkboxes accepted before borrow pickup</li>
      <li><strong>Terms of Service acceptance</strong> &mdash; recorded at registration and when new versions are published</li>
      <li><strong>Search queries</strong> &mdash; the text you enter when searching for tools</li>
    </ul>

    <h3>Information Collected Automatically</h3>
    <p>When you use NeighborhoodTools, we automatically collect:</p>
    <ul>
      <li><strong>IP address</strong> &mdash; recorded in server logs, rate-limiting systems, search logs, and Content Security Policy (CSP) violation reports for security and abuse prevention</li>
      <li><strong>Session ID</strong> &mdash; a PHP session cookie used for authentication and CSRF protection; also stored in search logs alongside your account ID</li>
      <li><strong>Browser and device information</strong> &mdash; User-Agent headers recorded in server logs for debugging</li>
      <li><strong>Cloudflare Turnstile challenge token</strong> &mdash; generated by the Turnstile widget on login, registration, forgot-password, and reset-password forms for bot detection</li>
      <li><strong>CSP violation reports</strong> &mdash; automatically sent by your browser when a Content Security Policy violation occurs; logged with IP address, violated directive, blocked URI, and source file</li>
      <li><strong>Timestamps</strong> &mdash; recorded for every account action (login, borrow, rating, etc.) for record-keeping and session timeout enforcement</li>
    </ul>

    <h3>Information from Third Parties</h3>
    <ul>
      <li><strong>Google Geocoding API</strong> &mdash; latitude and longitude for your address, used solely to resolve your neighborhood ID; coordinates are not stored on your account record</li>
      <li><strong>Stripe</strong> &mdash; payment confirmation and Payment Intent ID when a security deposit is processed</li>
    </ul>
  </section>

  <section id="how-we-use">
    <h2>How We Use Your Information</h2>
    <ol>
      <li><strong>Account creation and authentication</strong> &mdash; name, username, email, password hash, ZIP code, and neighborhood to create and secure your account</li>
      <li><strong>Profile display</strong> &mdash; first name, last name, username, bio, avatar, neighborhood, and member-since date are shown publicly on your profile; email and street address are never displayed publicly</li>
      <li><strong>Tool lending and borrowing</strong> &mdash; tool details, borrow requests, loan duration, notes, pickup/return codes, and deposit amounts to facilitate transactions between neighbors</li>
      <li><strong>Payments and deposits</strong> &mdash; Stripe processes card payments for security deposits; we store only the payment confirmation ID and amount, never your card number</li>
      <li><strong>Communication</strong> &mdash; in-app notifications for borrow requests, approvals, denials, due-date reminders, return confirmations, and rating requests; email is used only for password reset links (sent to the address you registered with)</li>
      <li><strong>Ratings and reputation</strong> &mdash; aggregated scores displayed publicly to help neighbors make informed lending and borrowing decisions; individual review text is attributed to the reviewer&rsquo;s first name</li>
      <li><strong>Search functionality</strong> &mdash; search queries logged with account ID (if logged in), IP address, and session ID to improve search results and monitor for abuse</li>
      <li><strong>Security and abuse prevention</strong> &mdash; IP address, session data, CSRF tokens, rate-limiting counters, honeypot fields, Cloudflare Turnstile challenge tokens, and CSP violation reports to protect against bots, brute-force attacks, and unauthorized access</li>
      <li><strong>Geolocation</strong> &mdash; street address sent to Google Geocoding API solely to resolve your neighborhood; coordinates are not stored on your account record</li>
      <li><strong>Dispute resolution</strong> &mdash; incident reports, dispute messages, and admin notes to mediate issues between lenders and borrowers</li>
      <li><strong>Legal compliance</strong> &mdash; TOS acceptance records (account ID, version, timestamp) to document consent</li>
      <li><strong>Platform administration</strong> &mdash; aggregated statistics (member count, tool count, active borrows) for site operation; admins can view individual account details to enforce community guidelines</li>
    </ol>
  </section>

  <section id="how-we-share">
    <h2>How We Share Your Information</h2>
    <p><strong>We do not sell your personal data. We do not share it with advertisers.</strong></p>
    <p>We share information only in the following limited circumstances:</p>
    <ul>
      <li><strong>Other NeighborhoodTools members</strong> &mdash; first name, last name, neighborhood, bio, avatar, tool listings, and ratings, as required for the lending and borrowing platform to function</li>
      <li><strong>Cloudflare (Turnstile)</strong> &mdash; IP address, browser signals, and challenge token for bot detection on authentication forms; Cloudflare acts as a data processor and uses this data only to provide the Turnstile anti-bot service</li>
      <li><strong>Google (Geocoding API)</strong> &mdash; street address and ZIP code for one-time neighborhood resolution during registration; Google&rsquo;s Cloud API Terms of Service apply</li>
      <li><strong>Stripe</strong> &mdash; payment amount, currency, and deposit/account metadata for deposit processing; Stripe acts as a data processor; card details are entered directly into Stripe&rsquo;s payment element and never touch our server</li>
      <li><strong>Law enforcement</strong> &mdash; any data, if legally compelled, in response to valid legal process (subpoena, court order, or equivalent)</li>
    </ul>
  </section>

  <section id="cookies">
    <h2>Cookies and Session Data</h2>
    <p>NeighborhoodTools uses a single essential cookie:</p>
    <ul>
      <li><strong>PHPSESSID</strong> (session cookie) &mdash; maintains your login state and CSRF protection. Expires when you close your browser or after 30 minutes of inactivity. Flags: <code>HttpOnly</code>, <code>Secure</code>, <code>SameSite=Lax</code>.</li>
    </ul>
    <p>Cloudflare Turnstile may set a short-lived challenge-clearance cookie (<strong>cf_clearance</strong>) on authentication pages, lasting up to 30 minutes.</p>
    <p>We do not use:</p>
    <ul>
      <li>Analytics cookies (no Google Analytics, Mixpanel, Hotjar, etc.)</li>
      <li>Advertising or tracking cookies</li>
      <li>Third-party social media cookies</li>
      <li>Persistent first-party cookies beyond the session cookie</li>
    </ul>
  </section>

  <section id="data-retention">
    <h2>How Long We Keep Your Information</h2>
    <ul>
      <li><strong>Account data</strong> (name, email, profile) &mdash; retained while your account is active; soft-deleted accounts are marked inactive but records are preserved for dispute and transaction history integrity</li>
      <li><strong>Password hash</strong> &mdash; retained until changed by you or your account is deleted</li>
      <li><strong>Password reset tokens</strong> &mdash; expire after 1 hour; consumed on use</li>
      <li><strong>Session data</strong> &mdash; deleted after 30 minutes of inactivity</li>
      <li><strong>Rate-limiting records</strong> &mdash; automatically purged after the rate window expires (15 minutes to 1 hour depending on the action)</li>
      <li><strong>Borrow and transaction history</strong> &mdash; retained indefinitely for record-keeping and dispute resolution</li>
      <li><strong>Ratings and reviews</strong> &mdash; retained indefinitely as part of the public reputation system</li>
      <li><strong>Search logs</strong> &mdash; approximately 30 days; purged weekly by automated cleanup</li>
      <li><strong>Tool and profile photos</strong> &mdash; retained while the tool or profile exists; old images are deleted when replaced</li>
      <li><strong>Incident reports and photos</strong> &mdash; retained indefinitely for platform safety records</li>
      <li><strong>TOS acceptance records</strong> &mdash; retained indefinitely for compliance documentation</li>
      <li><strong>CSP violation logs</strong> &mdash; retained per server log configuration</li>
      <li><strong>Server error logs</strong> &mdash; retained per server configuration (not controlled by the application)</li>
    </ul>
  </section>

  <section id="data-security">
    <h2>How We Protect Your Information</h2>
    <p>We take the security of your data seriously and implement industry-standard safeguards, including:</p>
    <ul>
      <li><strong>Encryption</strong> &mdash; all connections are encrypted in transit; passwords are stored using a strong one-way hash and are never retained in plaintext</li>
      <li><strong>Session protection</strong> &mdash; sessions expire after periods of inactivity and are secured against common web-based attacks</li>
      <li><strong>Input and output safeguards</strong> &mdash; all user-supplied data is validated on the server and sanitized before display to prevent injection and scripting attacks</li>
      <li><strong>Rate limiting</strong> &mdash; automated safeguards are in place to prevent brute-force and abuse attempts</li>
      <li><strong>Bot protection</strong> &mdash; authentication forms are protected by Cloudflare Turnstile to distinguish real users from automated scripts</li>
      <li><strong>Upload validation</strong> &mdash; uploaded files are verified by type and size before being accepted</li>
      <li><strong>Access controls</strong> &mdash; role-based permissions ensure users can only access data and actions appropriate to their account</li>
      <li><strong>Security headers</strong> &mdash; the platform sends browser-level directives that reduce exposure to common attack vectors</li>
    </ul>
    <p>No system is completely secure. If you believe your account has been compromised, please <a href="mailto:contact@neighborhoodtools.org">contact us</a> immediately.</p>
  </section>

  <section id="your-rights">
    <h2>Your Rights</h2>
    <ol>
      <li><strong>Access</strong> &mdash; you can view all personal data associated with your account via your profile page</li>
      <li><strong>Correction</strong> &mdash; you can update your name, address, bio, and avatar at any time through your profile settings; username and email cannot be changed at this time</li>
      <li><strong>Deletion</strong> &mdash; you can request account deletion by contacting us; accounts are soft-deleted (marked inactive) to preserve transaction history integrity; personally identifiable fields can be anonymized on request</li>
      <li><strong>Data portability</strong> &mdash; you can request a copy of your personal data in a structured format by contacting us</li>
      <li><strong>Restrict processing</strong> &mdash; you can request that we limit how we use your data while a complaint is being resolved</li>
      <li><strong>Withdraw consent</strong> &mdash; where processing is based on consent, you may withdraw it at any time (this does not affect prior lawful processing)</li>
      <li><strong>Notification preferences</strong> &mdash; you can opt out of due-date reminders, return confirmations, and rating alerts via your notification settings; borrow workflow notifications (requests, approvals, denials) cannot be disabled as they are essential to the service</li>
      <li><strong>Search history</strong> &mdash; search queries are logged for platform improvement and automatically purged after 30 days; contact us if you want your search history purged sooner</li>
    </ol>

    <h3>For California Residents (CCPA)</h3>
    <ul>
      <li>We do not sell personal information</li>
      <li>We do not share personal information for cross-context behavioral advertising</li>
      <li>You have the right to know what data we collect, request deletion, and opt out of sale (not applicable since we do not sell)</li>
    </ul>

    <h3>For EU/EEA Residents (GDPR)</h3>
    <ul>
      <li>Legal basis for processing: contract performance (account, transactions), legitimate interest (security, abuse prevention, search improvement), consent (Cloudflare Turnstile, optional profile data)</li>
      <li>You may lodge a complaint with your local data protection authority</li>
    </ul>
  </section>

  <section id="children">
    <h2>Children&rsquo;s Privacy</h2>
    <p>NeighborhoodTools requires all users to be at least 18 years old. The platform is not directed at children or minors. Users must affirm their age during registration. We do not knowingly collect personal data from anyone under 18. If we become aware that a minor has provided personal data, we will delete the account and associated data promptly.</p>
    <p>Parents or guardians who believe their child has provided data can <a href="mailto:contact@neighborhoodtools.org">contact us</a> for removal.</p>
  </section>

  <section id="third-party">
    <h2>Third-Party Services</h2>

    <h3>Cloudflare Turnstile</h3>
    <ul>
      <li><strong>Purpose:</strong> bot detection on login, registration, forgot-password, and reset-password forms</li>
      <li><strong>Data collected by Cloudflare:</strong> IP address, browser signals, challenge token</li>
      <li><strong>Cloudflare&rsquo;s role:</strong> data processor &mdash; data used only to provide the Turnstile anti-bot service</li>
      <li><strong>More info:</strong> <a href="https://www.cloudflare.com/privacypolicy/" rel="noopener">Cloudflare Privacy Policy</a></li>
    </ul>

    <h3>Google Geocoding API</h3>
    <ul>
      <li><strong>Purpose:</strong> one-time address-to-neighborhood resolution during registration</li>
      <li><strong>Data sent:</strong> street address and ZIP code</li>
      <li><strong>Data retained by Google:</strong> subject to Google Cloud Platform Terms of Service</li>
      <li><strong>More info:</strong> <a href="https://cloud.google.com/maps-platform/terms" rel="noopener">Google Maps Platform Terms</a></li>
    </ul>

    <h3>Stripe</h3>
    <ul>
      <li><strong>Purpose:</strong> security deposit payment processing</li>
      <li><strong>Data handled by Stripe:</strong> card number, expiration, and CVC (entered directly into Stripe&rsquo;s payment element &mdash; never touches our server), payment amount, and currency</li>
      <li><strong>Stripe&rsquo;s role:</strong> data processor and independent controller for payment fraud prevention</li>
      <li><strong>More info:</strong> <a href="https://stripe.com/privacy" rel="noopener">Stripe Privacy Policy</a></li>
    </ul>
  </section>

  <section id="data-transfers">
    <h2>International Data Transfers</h2>
    <p>NeighborhoodTools is hosted in the United States. Third-party processors (Cloudflare, Google, Stripe) may process data in various countries. Where transfers occur outside your jurisdiction, they are protected by the processor&rsquo;s standard contractual clauses and certifications.</p>
  </section>

  <section id="changes">
    <h2>Changes to This Policy</h2>
    <p>We may update this policy to reflect changes in our practices or legal requirements. Material changes will be communicated via in-app notification. The &ldquo;Last Updated&rdquo; date at the top of this policy will always reflect the most recent revision. Continued use of NeighborhoodTools after changes constitutes acceptance of the updated policy.</p>
  </section>

  <section id="contact">
    <h2>Contact Us</h2>
    <p>For privacy inquiries, contact us at <a href="mailto:contact@neighborhoodtools.org">contact@neighborhoodtools.org</a>. We aim to respond within 30 days.</p>
  </section>
</div>
